version: '3.9'

services:
  gsi:
    build:
      context: .
      args:
        - IMAGE=$IMAGE
    image: gsi
    container_name: gsi
    network_mode: host
    userns_mode: host
    volumes:
      - ${PREFIX:-/usr/local}:/tmp/dst${PREFIX:-/usr/local}
      - /etc:/tmp/etc
      - /usr/local/share:/tmp/usr/local/share
      - ./var/cache/gsi:/tmp/var/cache/gsi
    environment:
      - DESTDIR=/tmp/src
      - FINALDIR=/tmp/dst
      - GIT_VERSION=${GIT_VERSION}
      - PREFIX=${PREFIX:-/usr/local}
      - MODE=${MODE:-install}
    env_file:
      - build.env
